openapi: 3.0.3
info:
  title: 'Employee API docs'
  description: 'Employee API docs'
  version: 1.0.0
servers:
  -
    url: 'http://employee-api.test'
paths:
  /api/v1/login:
    post:
      summary: Login
      operationId: login
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  access_token: 2|sB3OxyfAoIHQX5zVPk5mp3ngtzm4Of72l0N3CuBR3e405f9e
                properties:
                  access_token:
                    type: string
                    example: 2|sB3OxyfAoIHQX5zVPk5mp3ngtzm4Of72l0N3CuBR3e405f9e
      tags:
        - Auth
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: test@example.com
                password:
                  type: string
                  description: ''
                  example: password
      security: []
  /api/v1/forgot-password:
    post:
      summary: 'Forgot Password'
      operationId: forgotPassword
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'We have emailed your password reset link.'
                properties:
                  message:
                    type: string
                    example: 'We have emailed your password reset link.'
      tags:
        - Auth
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: test@example.com
      security: []
  /api/v1/reset-password:
    post:
      summary: 'Reset Password'
      operationId: resetPassword
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Your password has been reset.'
                properties:
                  message:
                    type: string
                    example: 'Your password has been reset.'
      tags:
        - Auth
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: e2a877917ecde7664093b16d525d0787c0ff2eae33a7a5372fe9f3e7364e6680
                email:
                  type: string
                  description: ''
                  example: test@example.com
                password:
                  type: string
                  description: ''
                  example: password
                password_confirmation:
                  type: string
                  description: ''
                  example: password
      security: []
  /api/v1/employees:
    get:
      summary: 'Index Employee'
      operationId: indexEmployee
      description: ''
      parameters:
        -
          in: query
          name: include
          description: ''
          example: employeeAddress
          required: false
          schema:
            type: string
            description: ''
            example: employeeAddress
        -
          in: query
          name: 'filter[full_name]'
          description: ''
          example: sint
          required: false
          schema:
            type: string
            description: ''
            example: sint
        -
          in: query
          name: 'filter[email]'
          description: ''
          example: adipisci
          required: false
          schema:
            type: string
            description: ''
            example: adipisci
        -
          in: query
          name: 'filter[position]'
          description: ''
          example: mollitia
          required: false
          schema:
            type: string
            description: ''
            example: mollitia
        -
          in: query
          name: sort
          description: ''
          example: qui
          required: false
          schema:
            type: string
            description: ''
            example: qui
        -
          in: query
          name: 'page[number]'
          description: ''
          example: 15
          required: false
          schema:
            type: integer
            description: ''
            example: 15
        -
          in: query
          name: 'page[size]'
          description: ''
          example: 20
          required: false
          schema:
            type: integer
            description: ''
            example: 20
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 99
                      full_name: 'Marielle Kuhic'
                      email: royal93@example.net
                      phone_number: '(660) 510-1313'
                      average_salary_last_year: '41.77'
                      position: tester
                      created_at: '2023-12-18T19:29:30.000000Z'
                      updated_at: '2023-12-18T19:29:30.000000Z'
                    -
                      id: 100
                      full_name: 'Heidi Hermiston'
                      email: sporer.ahmed@example.com
                      phone_number: '+1 (930) 347-9985'
                      average_salary_last_year: '0.89'
                      position: pm
                      created_at: '2023-12-18T19:29:30.000000Z'
                      updated_at: '2023-12-18T19:29:30.000000Z'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 99
                        full_name: 'Marielle Kuhic'
                        email: royal93@example.net
                        phone_number: '(660) 510-1313'
                        average_salary_last_year: '41.77'
                        position: tester
                        created_at: '2023-12-18T19:29:30.000000Z'
                        updated_at: '2023-12-18T19:29:30.000000Z'
                      -
                        id: 100
                        full_name: 'Heidi Hermiston'
                        email: sporer.ahmed@example.com
                        phone_number: '+1 (930) 347-9985'
                        average_salary_last_year: '0.89'
                        position: pm
                        created_at: '2023-12-18T19:29:30.000000Z'
                        updated_at: '2023-12-18T19:29:30.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 99
                        full_name:
                          type: string
                          example: 'Marielle Kuhic'
                        email:
                          type: string
                          example: royal93@example.net
                        phone_number:
                          type: string
                          example: '(660) 510-1313'
                        average_salary_last_year:
                          type: string
                          example: '41.77'
                        position:
                          type: string
                          example: tester
                        created_at:
                          type: string
                          example: '2023-12-18T19:29:30.000000Z'
                        updated_at:
                          type: string
                          example: '2023-12-18T19:29:30.000000Z'
      tags:
        - Employee
      security: []
    post:
      summary: 'Store Employee'
      operationId: storeEmployee
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 101
                    full_name: 'Prof. Natalie Doyle II'
                    email: kathryne.bernier@example.net
                    phone_number: '(781) 547-4750'
                    average_salary_last_year: '22.51'
                    position: front-end
                    created_at: '2023-12-18T19:29:30.000000Z'
                    updated_at: '2023-12-18T19:29:30.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 101
                      full_name:
                        type: string
                        example: 'Prof. Natalie Doyle II'
                      email:
                        type: string
                        example: kathryne.bernier@example.net
                      phone_number:
                        type: string
                        example: '(781) 547-4750'
                      average_salary_last_year:
                        type: string
                        example: '22.51'
                      position:
                        type: string
                        example: front-end
                      created_at:
                        type: string
                        example: '2023-12-18T19:29:30.000000Z'
                      updated_at:
                        type: string
                        example: '2023-12-18T19:29:30.000000Z'
      tags:
        - Employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                  description: ''
                  example: illum
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 254 characters.'
                  example: wisoky.brigitte@example.net
                phone_number:
                  type: string
                  description: ''
                  example: placeat
                average_salary_last_year:
                  type: integer
                  description: ''
                  example: 14
                position:
                  type: string
                  description: ''
                  example: pm
                  enum:
                    - front-end
                    - back-end
                    - pm
                    - designer
                    - tester
                employee_address:
                  type: object
                  description: ''
                  example: []
                  properties:
                    residence_country:
                      type: string
                      description: ''
                      example: quasi
                    residence_zip_code:
                      type: string
                      description: ''
                      example: veniam
                    residence_city:
                      type: string
                      description: ''
                      example: laudantium
                    residence_street:
                      type: string
                      description: ''
                      example: et
                    residence_building_number:
                      type: string
                      description: ''
                      example: occaecati
                    residence_apartment_number:
                      type: string
                      description: ''
                      example: null
                    different_correspondence_address:
                      type: boolean
                      description: ''
                      example: false
                    correspondence_country:
                      type: string
                      description: ''
                      example: harum
                    correspondence_zip_code:
                      type: string
                      description: ''
                      example: null
                    correspondence_city:
                      type: string
                      description: ''
                      example: et
                    correspondence_street:
                      type: string
                      description: ''
                      example: iure
                    correspondence_building_number:
                      type: string
                      description: ''
                      example: null
                    correspondence_apartment_number:
                      type: string
                      description: ''
                      example: null
              required:
                - full_name
                - email
                - position
                - employee_address
    delete:
      summary: 'Bulk Destroy Employee'
      operationId: bulkDestroyEmployee
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Employee
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                employee_ids:
                  type: array
                  description: ''
                  example:
                    - dolores
                  items:
                    type: string
  '/api/v1/employees/{employee_id}':
    get:
      summary: 'Show Employee'
      operationId: showEmployee
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 102
                    full_name: 'Amelie Borer Sr.'
                    email: abbott.elenor@example.net
                    phone_number: '(740) 986-4248'
                    average_salary_last_year: '0.97'
                    position: tester
                    created_at: '2023-12-18T19:29:30.000000Z'
                    updated_at: '2023-12-18T19:29:30.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 102
                      full_name:
                        type: string
                        example: 'Amelie Borer Sr.'
                      email:
                        type: string
                        example: abbott.elenor@example.net
                      phone_number:
                        type: string
                        example: '(740) 986-4248'
                      average_salary_last_year:
                        type: string
                        example: '0.97'
                      position:
                        type: string
                        example: tester
                      created_at:
                        type: string
                        example: '2023-12-18T19:29:30.000000Z'
                      updated_at:
                        type: string
                        example: '2023-12-18T19:29:30.000000Z'
      tags:
        - Employee
    put:
      summary: 'Update Employee'
      operationId: updateEmployee
      description: ''
      parameters: []
      responses:
        202:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 103
                    full_name: 'Micheal Witting'
                    email: zoey.ruecker@example.com
                    phone_number: 929.655.8391
                    average_salary_last_year: '5399312.51'
                    position: back-end
                    created_at: '2023-12-18T19:29:30.000000Z'
                    updated_at: '2023-12-18T19:29:30.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 103
                      full_name:
                        type: string
                        example: 'Micheal Witting'
                      email:
                        type: string
                        example: zoey.ruecker@example.com
                      phone_number:
                        type: string
                        example: 929.655.8391
                      average_salary_last_year:
                        type: string
                        example: '5399312.51'
                      position:
                        type: string
                        example: back-end
                      created_at:
                        type: string
                        example: '2023-12-18T19:29:30.000000Z'
                      updated_at:
                        type: string
                        example: '2023-12-18T19:29:30.000000Z'
      tags:
        - Employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                  description: ''
                  example: eius
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 254 characters.'
                  example: hazle.hand@example.org
                phone_number:
                  type: string
                  description: ''
                  example: commodi
                average_salary_last_year:
                  type: integer
                  description: ''
                  example: 15
                position:
                  type: string
                  description: ''
                  example: front-end
                  enum:
                    - front-end
                    - back-end
                    - pm
                    - designer
                    - tester
                employee_address:
                  type: object
                  description: ''
                  example: []
                  properties:
                    residence_country:
                      type: string
                      description: ''
                      example: quidem
                    residence_zip_code:
                      type: string
                      description: ''
                      example: illo
                    residence_city:
                      type: string
                      description: ''
                      example: nesciunt
                    residence_street:
                      type: string
                      description: ''
                      example: cum
                    residence_building_number:
                      type: string
                      description: ''
                      example: cum
                    residence_apartment_number:
                      type: string
                      description: ''
                      example: null
                    different_correspondence_address:
                      type: boolean
                      description: ''
                      example: true
                    correspondence_country:
                      type: string
                      description: ''
                      example: adipisci
                    correspondence_zip_code:
                      type: string
                      description: ''
                      example: null
                    correspondence_city:
                      type: string
                      description: ''
                      example: quo
                    correspondence_street:
                      type: string
                      description: ''
                      example: amet
                    correspondence_building_number:
                      type: string
                      description: ''
                      example: null
                    correspondence_apartment_number:
                      type: string
                      description: ''
                      example: null
              required:
                - full_name
                - email
                - position
                - employee_address
    parameters:
      -
        in: path
        name: employee_id
        description: 'The ID of the employee.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/employees/{id}':
    delete:
      summary: 'Destroy Employee'
      operationId: destroyEmployee
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Employee
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the employee.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Auth
    description: ''
  -
    name: Employee
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'To obtain a token use the Login endpoint (email: test@example.com, password: password)'
security:
  -
    default: []
